CORES = {
    'ARC': (
        'fba_lite',
        'fbalpha2012',
        'fbneo',
        'mame2000',
        'mame2003',
        'mame2003_plus',
        'fbneo_xtreme',
        'mame2003_xtreme',
    ),
    'GBA': ('gpsp', 'mgba', 'vba_next'),
    'GBC': ('gambatte', 'tgbdual'),
    'MD': ('genesis_plus_gx', 'genesis_plus_gx_wide', 'picodrive'),
    'NES': ('fceumm', 'nestopia'),
    'NGP': ('mednafen_ngp',),
    'PCE': ('mednafen_pce_fast', 'mednafen_supergrafx'),
    'PS1': ('pcsx_rearmed',),
    'SNES': ('snes9x2002', 'snes9x2005', 'snes9x2010', 'supafaust', 'chimerasnes'),
    'WSC': ('mednafen_wswan',),
    'ATARI2600': ('stella2014',),
    'ATARI5200': ('atari800',),
    'ATARI7800': ('prosystem',),
    'ATARIST': ('hatari',),
    'DOS': ('dosbox_pure', 'dosbox_svn'),
    'VECTREX': ('vecx',),
    'AMIGA': ('uae4arm',),
    'ZXS': ('fuse',),
    'NEOCD': ('neocd',),
    'PC98': ('nekop2',),
    'MSX': ('fmsx', 'bluemsx'),
}

NAMES = {
    'atari800': 'Atari 800',
    'dosbox_pure': 'DOSBox Pure',
    'dosbox_svn': 'DOSBox SVN',
    'fbalpha2012': 'FinalBurn Alpha 2012',
    'fba_lite': 'FinalBurn Alpha Lite',
    'fbneo': 'FinalBurn Neo',
    'fceumm': 'FCEUmm',
    'gambatte': 'Gambatte',
    'genesis_plus_gx': 'Genesis Plus GX',
    'genesis_plus_gx_wide': 'Genesis Plus GX Wide',
    'gpsp': 'gpSP',
    'mame2000': 'MAME 2000',
    'mame2003': 'MAME 2003',
    'mame2003_plus': 'MAME 2003 Plus',
    'mednafen_ngp': 'Mednafen NeoPop',
    'mednafen_pce_fast': 'Mednafen PCE Fast',
    'mednafen_supergrafx': 'Mednafen PCE SuperGrafx',
    'mednafen_wswan': 'Mednafen Wswan',
    'mgba': 'mGBA',
    'nestopia': 'Nestopia',
    'pcsx_rearmed': 'PCSX ReARMed',
    'picodrive': 'PicoDrive',
    'prosystem': 'ProSystem',
    'snes9x2002': 'Snes9x 2002',
    'snes9x2005': 'Snes9x 2005',
    'snes9x2010': 'Snes9x 2010',
    'supafaust': 'Mednafen Supafaust',
    'stella2014': 'Stella 2014',
    'vba_next': 'VBA Next',
    'vecx': 'vecx',
    'uae4arm': 'uae4arm',
    'fuse': 'fuse',
    'neocd': 'neocd',
    'hatari': 'Hatari',
    'fbneo_xtreme': 'FinalBurn Neo Xtreme',
    'mame2003_xtreme': 'MAME 2003 Xtreme',
    'chimerasnes': 'Chimera SNES',
    'tgbdual': 'TGB Dual',
    'nekop2': 'Neko Project II',
    'fmsx': "Marat Fayzullin's fMSX",
}
