CORES = {
    'ARC': (
        'fba_lite',
        'fbalpha2012',
        'fbneo',
        'mame2000',
        'mame2003',
        'mame2003_plus',
        'km_fbneo_xtreme_amped',
        'km_mame2003_xtreme_amped',
    ),
    'GBA': ('gpsp', 'mgba', 'vba_next'),
    'GBC': ('gambatte', 'tgbdual'),
    'MD': ('genesis_plus_gx', 'genesis_plus_gx_wide', 'picodrive'),
    'NES': ('fceumm', 'nestopia'),
    'NGP': ('mednafen_ngp',),
    'PCE': ('mednafen_pce_fast', 'mednafen_supergrafx'),
    'PS1': ('pcsx_rearmed',),
    'SNES': ('snes9x2002', 'snes9x2005_plus', 'snes9x', 'mednafen_supafaust', 'chimerasnes'),
    'WSC': ('mednafen_wswan',),
    'ATARI2600': ('stella2014',),
    'ATARI5200': ('atari800',),
    'ATARI7800': ('prosystem',),
    'ATARIST': ('hatari',),
    'DOS': ('dosbox_pure', 'dosbox_svn'),
    'VECTREX': ('vecx',),
    'AMIGA': ('uae4arm',),
    'ZXS': ('fuse',),
    'NEOCD': ('neocd',),
    'PC98': ('nekop2', 'np2kai'),
    'MSX': ('fmsx', 'bluemsx'),
    'C64': ('vice',),
    'X68000': ('px68k',),
    'LYNX': ('mednafen_lynx', 'handy'),
    'CPC': ('cap32', 'crocods'),
    'N64': ('parallel_n64',),
}

NAMES = {
    'atari800': 'Atari 800',
    'dosbox_pure': 'DOSBox Pure',
    'dosbox_svn': 'DOSBox SVN',
    'fbalpha2012': 'FinalBurn Alpha 2012',
    'fba_lite': 'FinalBurn Alpha Lite',
    'fbneo': 'FinalBurn Neo',
    'fceumm': 'FCEUmm',
    'gambatte': 'Gambatte',
    'genesis_plus_gx': 'Genesis Plus GX',
    'genesis_plus_gx_wide': 'Genesis Plus GX Wide',
    'gpsp': 'gpSP',
    'mame2000': 'MAME 2000',
    'mame2003': 'MAME 2003',
    'mame2003_plus': 'MAME 2003 Plus',
    'mednafen_ngp': 'Mednafen NeoPop',
    'mednafen_pce_fast': 'Mednafen PCE Fast',
    'mednafen_supergrafx': 'Mednafen PCE SuperGrafx',
    'mednafen_wswan': 'Mednafen Wswan',
    'mgba': 'mGBA',
    'nestopia': 'Nestopia',
    'pcsx_rearmed': 'PCSX ReARMed',
    'picodrive': 'PicoDrive',
    'prosystem': 'ProSystem',
    'snes9x2002': 'Snes9x 2002',
    'snes9x2005_plus': 'Snes9x 2005 Plus',
    'snes9x': 'Snes9x',
    'mednafen_supafaust': 'Mednafen Supafaust',
    'stella2014': 'Stella 2014',
    'vba_next': 'VBA Next',
    'vecx': 'vecx',
    'uae4arm': 'uae4arm',
    'fuse': 'fuse',
    'neocd': 'neocd',
    'hatari': 'Hatari',
    'km_fbneo_xtreme_amped': 'FinalBurn Neo Xtreme',
    'km_mame2003_xtreme_amped': 'MAME 2003 Xtreme',
    'chimerasnes': 'Chimera SNES',
    'tgbdual': 'TGB Dual',
    'nekop2': 'Neko Project II',
    'np2kai': 'Neko Project II kai',
    'fmsx': "Marat Fayzullin's fMSX",
    'bluemsx': 'blueMSX',
    'vice': 'VICE',
    'px68k': 'Portable (x)keropi PRO-68K',
    'mednafen_lynx': 'Beetle Lynx',
    'handy': 'Handy',
    'cap32': 'Caprice32',
    'crocods': 'CrocoDS',
    'parallel_n64': 'Mupen64Plus',
}
