#include "cores.h"

const CORE_STRUCT CORES[CORE_COUNT] = {
    {"gpsp", GPSP, GBA},
    {"vba_next", VBA_NEXT, GBA},
    {"gambatte", GAMBATTE, GBC},
    {"fba_lite", FBA_LITE, ARC},
    {"fbneo", FBNEO, ARC},
    {"fbalpha2012", FBALPHA2012, ARC},
    {"snes9x2002", SNES9X2002, SNES},
    {"snes9x2005", SNES9X2005, SNES},
    {"snes9x2010", SNES9X2010, SNES},
    {"fceumm", FCEUMM, NES},
    {"nestopia", NESTOPIA, NES},
    {"genesis_plus_gx", GENESIS_PLUS_GX, MD},
    {"genesis_plus_gx_wide", GENESIS_PLUS_GX_WIDE, MD},
    {"picodrive", PICODRIVE, MD},
    {"mednafen_pce_fast", MEDNAFEN_PCE_FAST, PCE},
    {"mednafen_supergrafx", MEDNAFEN_SUPERGRAFX, PCE},
    {"mednafen_ngp", MEDNAFEN_NGP, NGP},
    {"mednafen_wswan", MEDNAFEN_WSWAN, WSC},
    {"pcsx_rearmed", PCSX_REARMED, PS1},
    {"stella2014", STELLA2014, ATARI2600},
    {"prosystem", PROSYSTEM, ATARI7800},
    {"atari800", ATARI800, ATARI5200},
    {"dosbox_pure", DOSBOX_PURE, DOS},
    {"mame2003_plus", MAME2003_PLUS, ARC},
    {"mame2003", MAME2003, ARC},
    {"vecx", VECX, VECTREX},
    {"uae4arm", UAE4ARM, AMIGA},
    {"fuse", FUSE, ZXS},
    {"neocd", NEOCD, NEOGEOCD},
    {"supafaust", SUPAFAUST, SNES},
    {"fbneo_xtreme", FBNEO_XTREME, ARC},
    {"mame2003_xtreme", MAME2003_XTREME, ARC},
    {"chimerasnes", CHIMERASNES, SNES},
    {"tgbdual", TGBDUAL, GBC},
    {"nekop2", NEKOP2, PC98},
    {"fmsx", FMSX, MSX},
    {"bluemsx", BLUEMSX, MSX},
    {"nekop2kai", NEKOP2KAI, PC98},
    {"vice", VICE, C64},
    {"px68k", PX68K, X68000},
};
