#include "cores.h"

const CORE_STRUCT CORES[CORE_COUNT] = {
    {"gpsp", "GBA", GPSP, GBA},
    {"vba_next", "GBA", VBA_NEXT, GBA},
    {"gambatte", "GBC", GAMBATTE, GBC},
    {"fba_lite", "ARC", FBA_LITE, ARC},
    {"fbneo", "ARC", FBNEO, ARC},
    {"fbalpha2012", "ARC", FBALPHA2012, ARC},
    {"snes9x2002", "SNES", SNES9X2002, SNES},
    {"snes9x2005", "SNES", SNES9X2005, SNES},
    {"snes9x2010", "SNES", SNES9X2010, SNES},
    {"fceumm", "NES", FCEUMM, NES},
    {"nestopia", "NES", NESTOPIA, NES},
    {"genesis_plus_gx", "MD", GENESIS_PLUS_GX, MD},
    {"genesis_plus_gx_wide", "MD", GENESIS_PLUS_GX_WIDE, MD},
    {"picodrive", "MD", PICODRIVE, MD},
    {"mednafen_pce_fast", "PCE", MEDNAFEN_PCE_FAST, PCE},
    {"mednafen_supergrafx", "PCE", MEDNAFEN_SUPERGRAFX, PCE},
    {"mednafen_ngp", "NGP", MEDNAFEN_NGP, NGP},
    {"mednafen_wswan", "WSC", MEDNAFEN_WSWAN, WSC},
    {"pcsx_rearmed", "PS1", PCSX_REARMED, PS1},
    {"stella2014", "ATARI2600", STELLA2014, ATARI2600},
    {"prosystem", "ATARI7800", PROSYSTEM, ATARI7800},
    {"atari800", "ATARI5200", ATARI800, ATARI5200},
    {"dosbox_pure", "DOS", DOSBOX_PURE, DOS},
    {"mame2003_plus", "ARC", MAME2003_PLUS, ARC},
    {"mame2003", "ARC", MAME2003, ARC},
    {"vecx", "VECX", VECX, VECTREX},
    {"uae4arm", "AMIGA", UAE4ARM, AMIGA},
    {"fuse", "ZXS", FUSE, ZXS},
    {"neocd", "NEOGEOCD", NEOCD, NEOGEOCD},
    {"supafaust", "SNES", SUPAFAUST, SNES},
    {"fbneo_xtreme", "ARC", FBNEO_XTREME, ARC},
    {"mame2003_xtreme", "ARC", MAME2003_XTREME, ARC},
    {"chimerasnes", "SNES", CHIMERASNES, SNES},
    {"tgbdual", "GBC", TGBDUAL, GBC},
    {"nekop2", "PC98", NEKOP2, PC98},
    {"fmsx", "MSX", FMSX, MSX},
    {"bluemsx", "MSX", BLUEMSX, MSX},
    {"nekop2kai", "PC98", NEKOP2KAI, PC98},
    {"vice", "C64", VICE, C64},
    {"px68k", "X68000", PX68K, X68000},
};
